### ISSUE TITLE
"Improvement of Security" != "Improvement of Security Belt Rank" still not clear

### ISSUE THREAD

**Issue by bob5ec** [AppSecure-nrw/security-belts#12]
Teams commonly understand [white/continuously-improve-your-security-belt-rank.md](https://github.com/AppSecure-nrw/security-belts/blob/master/white/continuously-improve-your-security-belt-rank.md) as "fulfill security requirements someone else is imposing on you".

Detailed discussion with teams will follow to find out why the get it wrong.

**Comment by mvollmary** [comment]
PR merged
