### ISSUE TITLE
Feedback on "review security belt activities"

### ISSUE THREAD

**Issue by wurstbrot** [AppSecure-nrw/security-belts#3]
This is more a brain dump as I am not having a better idea.

As a security guild leader, I want to have discussions about implementation of activities and problems with it.

Sometimes, it leads to providing more work to the team implementing it because "requirements" are raised by other teams. E.g. "you define a quality gate in Jenkins, it would be good to have xyz in addition". This is good for security in general.
This might lead to less activities from that team because of overloads from other teams.

In addition I feel that basics like "Definition of a quality gate" should be done by a centralized team, so the sharing/review here is about the problems of the current policies and guidelines. At least a guideline should be provided and teams might adapt it. I give out the guideline "a container shouldn't be based on an image older than X days" and some teams do adopt this to Y days.

From my understanding, the security-belts here are to give devops teams a guideline and are not focused on the activities of security teams. By following this definition, I wouldn't add more.

In case there would be a security team focus: The security team will have to moderate the discussions and might motivate teams to implement more or to step in when wishes of other teams are too big.

**Comment by StefanDziwok** [comment]
Hey Timo, thanks for all the feedback. Here are some answers that we came up with yesterday:

**Feedback:** Giving or receiving feedback on a regular basis should be part of the guild meeting. We will add this to the methodology.

**Quality Gates:** We will add the following infos: It is important that the Quality Gates meet or implement all requirements of the policy. It may be possible and useful to define a standard set of quality gates centrally (this is a task of the guild, not the team). 

**Policy:** We will add to the activities that depend on the policy that teams should inform the guild if they think that the policy should be expanded.

**Security Teams:** Currently, we only address devops teams and not security teams. In our opinion, the security team that you mentioned should be the guild and not a central security department. In the future, we could create an extra checklist for the guild for managing the security belts and motivating the teams, e.g., what do I have to prepare for when a team soon has the yellow belt? Maybe, we also need all belts from the point of view of the guild.

**Comment by StefanDziwok** [comment]
> Sometimes, it leads to providing more work to the team implementing it because "requirements" are raised by other teams. E.g. "you define a quality gate in Jenkins, it would be good to have xyz in addition". This is good for security in general.
> This might lead to less activities from that team because of overloads from other teams.

For this topic, we currently have no answer for you. Do you have a proposal or is it an open problem for you as well?

**Comment by wurstbrot** [comment]
That is an open problem.

**Comment by mvollmary** [comment]
All suggestions are implemented. Thanks for the feedback
