### ISSUE TITLE
Add Literature for each Design Principle

### ISSUE THREAD

**Issue by StefanDziwok** [AppSecure-nrw/security-belts#64]
We need literature for each Design Principle based on the following ticket: 
https://github.com/AppSecure-nrw/security-belts/blob/securityByDesign/orange/follow-security-by-design-principles.md

In contrast to the initial task, please list them in the corresponding wiki file. Moreover, we need a description on our own as we realized that most definitions will not be sufficient for our goal that they are easily understandable.

Please write in this ticket if no useful definition for a singular principle exists.
https://github.com/AppSecure-nrw/security-belts/wiki/Security-by-Design-Principles

##########
As a start, you should have a look at the following literature. Additionally, you can add them to the activity in the literature section if they are helpful in your opinion:

Design principles as presented by OWASP:
https://www.owasp.org/index.php/Security_by_Design_Principles

More design principles (Open Design, Separation of Privilege,…):
http://www.informit.com/articles/article.aspx?p=30487&seqNum=2

Least Privilege:
https://digitalguardian.com/blog/what-principle-least-privilege-polp-best-practice-information-security-and-compliance

Defense in Depth:
https://www.imperva.com/learn/application-security/defense-in-depth/

Eoin Woods on Security Design Principles (GOTO 2016):
https://www.youtube.com/watch?v=4qN3JBGd1g8

Top 10 Security Best Practices to secure your Microservices (AppSecUSA 2017): 
https://www.youtube.com/watch?v=VtUQINsYXDM

Dr. Sebastian Schrittwieser on Security by Obscurity in web applications (WeAreDevelopers 2018):
https://www.youtube.com/watch?v=UnjadBlHC5c

**Comment by StefanDziwok** [comment]
I updated the task description.

**Comment by SamiraTaaibi** [comment]
Initial overview of Security by Design Principles. An update with a brief description of the individual principles will follow.

[Security by Design Principles.docx](https://github.com/AppSecure-nrw/security-belts/files/6739910/Security.by.Design.Principles.docx)

**Comment by StefanDziwok** [comment]
@SamiraTaaibi 
Within the security belt meeting, we agreed on the following next steps:
* We agree to your proposal to write a description with your own words.
* You can add your top 3 literature references per principle.
* You can directly write within the Wiki but please do not change the headlines as they are referenced by the belt activity.

**Comment by mvollmary** [comment]
Review started, not jet finished. Next session we will look at 'No Security by Obscurity'

**Comment by SamiraTaaibi** [comment]
Potentially, we can omit the last principle _don't trust your supply chain_ and include it in the _don't trust principle_, since _don't trust services_ and _don't trust infrastructure_ are already included in this principle.

**Comment by mvollmary** [comment]
Done with review. We made some changes.
🥳
