### ISSUE TITLE
Ask visitors of Belt Websites to give feedback

### ISSUE THREAD

**Issue by bob5ec** [AppSecure-nrw/security-belts#68]
Evaluation of the Security Belts' Concept
https://www.surveymonkey.de/r/MC6JQR2

Evaluation of a singular Security Belt
https://www.surveymonkey.de/r/MJWT29X

Evaluation of the singular Belt Activity
https://www.surveymonkey.de/r/MNWNVRB

**Comment by StefanDziwok** [comment]
I added the green and blue belt and all new activities from yellow and orange to the "Evaluation of a singular Security Belt".

We also have to do this for the "Evaluation of the singular Belt Activity".
