### ISSUE TITLE
it-security-camp.de als Beispiel einfügen

### ISSUE THREAD

**Issue by StefanDziwok** [AppSecure-nrw/security-belts#87]
Das Angebot von Christian könnten wir beim gelben Gürtel beim regelmäßigen Training des Champions verlinken, auch wenn es deutsch ist.
https://github.com/AppSecure-nrw/security-belts/blob/master/orange/regular-security-training-of-security-champions.md

**Comment by mvollmary** [comment]
Training is only on German, we're searching for English trainings
