### ISSUE TITLE
Idea for changes due to feedback

### ISSUE THREAD

**Issue by mvollmary** [AppSecure-nrw/security-belts#88]
- [x] Weekly Review: instead of once every week -> on a regular basis (e.g. once every week/sprint)
-  [x] `Review Security Belt Activities`: make clear that this is a regular activity (get feedback early and often) and that this more something for later belts than the white one
- [x] `Unit Tests for Security Features`: the reader must be aware that he does not have to work through the whole OWASP testing guide

**Comment by StefanDziwok** [comment]
I have pinned this issue as @mvollmary stated that we should solve this issue with high priority such that our users see that we fix their reported problems.
